sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - npm run validate
after_success:
  - npx codecov
  - npx -p semantic-release@7 -c "semantic-release pre && npm publish && semantic-release post"
branches:
  only:
    - master
