sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '8'
before_script:
  - ls node_modules
  - ls node_modules/kcd-scripts
  - ls node_modules/kcd-scripts/node_modules || echo "no node_modules"
script:
  - npm run validate
after_success:
  - npx codecov
  - npx -p semantic-release@7 -c "semantic-release pre && npm publish && semantic-release post"
branches:
  only:
    - master
